server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    user:
      name: admin
      password: fiap
      roles: ADMIN