server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  security:
    user:
      name: admin
      password: fiap
      roles: ADMIN