POST http://localhost:8080/api/aluno
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="input.txt"

// The 'input.txt' file will be uploaded
< c:/Users/Bruno/Documents/Mba-Fiap/Spring/lista_alunos.txt

###

POST http://example.com/api/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="first"; filename="input.txt"

// The 'input.txt' file will be uploaded
< c:/Users/Bruno/Documents/Mba-Fiap/Spring/lista_alunos.txt

###