POST http://localhost:8080/api/aluno
Content-Type: application/json

{
  "rm": 171,
  "nome": "Bozonaro Luladrão da Dilma e Temer"
}

###

GET http://localhost:8080/api/aluno/171
Accept: application/json

###

GET http://localhost:8080/api/aluno/4821815
Accept: application/json

###




