POST http://localhost:8080/api/cartaoCredito
Content-Type: application/json

{
  "rmAluno": 4821815,
  "numero": 699,
  "digitoVerificador": 24
}

###

GET http://localhost:8080/api/cartaoCredito/aluno/4821815
Accept: application/json

###


GET http://localhost:8080/api/cartaoCredito/aluno/
Accept: application/json

###

