POST http://localhost:8080/api/importacao
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="input.txt"

// The 'input.txt' file will be uploaded
< c:/Users/Bruno/Documents/Mba-Fiap/Spring/lista_alunos.txt

###

GET http://localhost:8080/api/aluno/3372659
Accept: application/json

###

GET http://localhost:8080/api/aluno/4801015
Accept: application/json

###