POST http://localhost:8080/api/transacao
Content-Type: application/json

{
  "id": 1,
  "dataHoraCriacao": "2020-03-16T22:54:34",
  "valor": 100.0,
  "status": "AUTORIZADA",
  "codigoAutorizacao": "abshhscvoododvjvs",
  "numeroCartao": 4000000000010805
}

###

POST http://localhost:8080/api/transacao
Content-Type: application/json

{
  "id": 2,
  "dataHoraCriacao": "2020-03-28T12:27:34",
  "valor": 300.00,
  "status": "AUTORIZADA",
  "codigoAutorizacao": "abshasdhscvoododvjvs",
  "numeroCartao": 4000000000010805
}

###

GET http://localhost:8080/api/transacao/1299

###

POST http://localhost:8080/api/transacao/lista
Content-Type: application/json

[{
  "id": 1,
  "dataHoraCriacao": "2020-03-16T22:54:34",
  "valor": 100.0,
  "status": "AUTORIZADA",
  "codigoAutorizacao": "abshhscvoododvjvs",
  "numeroCartao": 4000000000010805
}]

###